# Generated by Django 4.0.3 on 2022-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.IntegerField()),
                ('zip_code', models.CharField(max_length=255)),
            ],
        ),
    ]
