# Generated by Django 4.0.3 on 2022-03-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizeduser',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
