# Generated by Django 4.0.3 on 2022-03-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_personalizeduser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personalizeduser',
            managers=[
            ],
        ),
    ]
