# Generated by Django 4.0.3 on 2022-03-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_instructor',
            field=models.OneToOneField(default=str, on_delete=django.db.models.deletion.CASCADE, to='kanvas.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='user_students',
            field=models.ManyToManyField(related_name='students', to='kanvas.user'),
        ),
    ]
