# Generated by Django 4.0.3 on 2022-03-14 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('demo_time', models.TimeField()),
                ('link_repo', models.CharField(max_length=255)),
                ('user_instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
