# Generated by Django 4.0.3 on 2022-03-17 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_courses_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user_instructor',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='user_students',
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='demo_time',
            field=models.DateTimeField(),
        ),
    ]
