# Generated by Django 4.0.3 on 2022-03-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='uuid',
            new_name='id',
        ),
    ]
