# Generated by Django 4.0.3 on 2022-03-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courses_user_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='demo_time',
            field=models.TimeField(),
        ),
    ]
