# Generated by Django 4.0.3 on 2022-03-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_uuid_courses_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='id',
            new_name='uuid',
        ),
    ]
